"""book_title table

Revision ID: 4f3b2ca36771
Revises: 
Create Date: 2022-02-15 21:59:59.407915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3b2ca36771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_title_author'), 'book_title', ['author'], unique=True)
    op.create_index(op.f('ix_book_title_book_title'), 'book_title', ['book_title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title_book_title'), table_name='book_title')
    op.drop_index(op.f('ix_book_title_author'), table_name='book_title')
    op.drop_table('book_title')
    # ### end Alembic commands ###
